server:  port: 8090

eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka  instance:    prefer-ip-address: true

spring:  application:    name: servicio-gateway-server
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:
          - Path=/api/productos/**
        filters:
          - StripPrefix=2          - EjemploCookie=Hola aqui mi mensaje personalizado, usuario, AndresGuzman # nombreFiltro = argumentos separados por comas#          - name: Ejemplo # Nombre[GatewayFilterFactory].java#            args:#              mensaje: Hola aqui mi mensaje personalizado#              cookieNombre: usuario#              cookieValor: AndresGuzman
      - id: servicio-items
        uri: lb://servicio-items
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2