server:  port: 8090

eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka  instance:    prefer-ip-address: true

spring:  application:    name: servicio-gateway-server
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:   # Condiciones que debe cumplir el request
          - Path=/api/productos/**#          - Header= token, \d+#          - Header= Content-Type, application/json#          - Method= GET, POST#          - Query= color  # si no se indica el valor solamente se requiere el parametro, da igual el valor#          - Cookie= color, azul
        filters:      # Filtros que se ejecutaran
          - StripPrefix=2          - EjemploCookie=Hola aqui mi mensaje personalizado, usuario, AndresGuzman # nombreFiltro = argumentos separados por comas#          - name: Ejemplo # Nombre[GatewayFilterFactory].java#            args:#              mensaje: Hola aqui mi mensaje personalizado#              cookieNombre: usuario#              cookieValor: AndresGuzman
      - id: servicio-items
        uri: lb://servicio-items
        predicates:   # Condiciones que debe cumplir
          - Path=/api/items/**
        filters:      # Filtros que se ejecutaran
          - StripPrefix=2          - AddRequestHeader=token-request, 12345       # Filtro predefinido para añadir contenido en la cabecera de la solicitud al servicio          - AddResponseHeader=token-response, 67890     # Filtro predefinido para añadir contenido en la cabecera de la respuesta al cliente          - SetResponseHeader=Content-Type, text/plain  # Filtro predefinido para editar contenido en la cabecera de la respuesta al cliente          - AddRequestParameter=nombre, Andres          # Filtro predefinido para añadir parametros en la solicitud a los servicios